services:
  mysql: 
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_db_app
      DB_USER: root
    volumes:
      - rails_db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - rails_docker

  app: 
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes: 
      - ".:/app"
    ports: 
      - "8080:3000"
    depends_on:
      - mysql
    environment:
      DB_USER: root
      DB_NAME: rails_db_app
      DB_PASSWORD: password
      DB_HOST: mysql
    networks:
      - rails_docker
volumes:
  rails_db_data:
    name: "rails_db_data"

networks:
  rails_docker:
    external: true